// Generated by scripts/generate-suite.ts. Do not edit directly.

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { markLifecyclePhase } from "./src/lifecycle-performance.ts";
import { importFreshSuiteRuntime, loadSuiteRuntime } from "./src/suite-loader.ts";

const ENTRY_PATH = fileURLToPath(import.meta.url);
const SOURCE_ROOT = join(dirname(ENTRY_PATH), "src");
const RUNTIME_PATH = join(SOURCE_ROOT, "suite-runtime.ts");

markLifecyclePhase("suite.wrapper.imported");

export default async function piStuff(pi: ExtensionAPI): Promise<void> {
	markLifecyclePhase("suite.wrapper.factory.start");
	const runtime = await loadSuiteRuntime({
		sourceRoot: SOURCE_ROOT,
		load: (_fingerprint, mode) =>
			mode === "initial" ? import("./src/suite-runtime.ts") : importFreshSuiteRuntime(RUNTIME_PATH),
	});
	await runtime.installPiStuff(pi, { childBaseExtensionPath: ENTRY_PATH });
	markLifecyclePhase("suite.wrapper.factory.end");
}
