import { afterEach, expect, mock, test } from "bun:test";
import { mkdir, mkdtemp, rm, truncate, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
import { parseJsonValue } from "../../../packages/pi-stuff/src/shared/json-value.js";
import { createExtensionContext } from "../../fixtures/extension-context.js";
import { toolRegistrationHarness } from "../../fixtures/tool-registration-host.js";

let nativeStdout = "";
const temporaryRoots: string[] = [];

mock.module("../../../packages/pi-stuff/src/codex/native-runner.js", () => ({
	parseNativeJson: (stdout: string) => parseJsonValue(stdout),
	runNativeTool: async () => ({ status: 0, stderr: "", stdout: nativeStdout }),
}));

const { registerCodexTools } = await import("../../../packages/pi-stuff/src/codex/tools.js");

const PNG_BYTES = Buffer.from(
	"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
	"base64",
);

interface FixtureNativeImage {
	readonly absolute_path?: string;
}

interface FixtureNativeImageResult {
	readonly images?: readonly FixtureNativeImage[];
	readonly path: number | string;
}

afterEach(async () => {
	await Promise.all(temporaryRoots.splice(0).map((root) => rm(root, { force: true, recursive: true })));
});

function imageModel(): NonNullable<ExtensionContext["model"]> {
	return {
		api: "openai-responses",
		baseUrl: "https://chatgpt.com/backend-api/codex/responses",
		contextWindow: 200_000,
		cost: { cacheRead: 0, cacheWrite: 0, input: 0, output: 0 },
		id: "gpt-5.2-codex",
		input: ["text", "image"],
		maxTokens: 32_000,
		name: "Codex",
		provider: "openai-codex",
		reasoning: true,
	};
}

async function executeImagegen(nativeResult: FixtureNativeImageResult) {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-"));
	temporaryRoots.push(root);
	const { host, tools } = toolRegistrationHarness();
	registerCodexTools(host);
	const tool = tools.get("imagegen");
	if (!tool) throw new Error("imagegen was not registered");
	const context = createExtensionContext({ cwd: root, model: imageModel() });
	Object.assign(context.modelRegistry, {
		getApiKeyAndHeaders: async () => ({
			apiKey: "test-token",
			headers: { "chatgpt-account-id": "test-account" },
			ok: true as const,
		}),
	});
	nativeStdout = JSON.stringify(nativeResult);
	return tool.execute("imagegen-test", { prompt: "draw a pixel" }, undefined, undefined, context);
}

function runImagegen(path: string) {
	return executeImagegen({ images: [{ absolute_path: path }], path: "generated.jpg" });
}

test("imagegen labels inline JPEG bytes with their detected MIME type", async () => {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-source-"));
	temporaryRoots.push(root);
	const path = join(root, "generated.jpg");
	const bytes = Buffer.from([0xff, 0xd8, 0xff, 0xe0]);
	await writeFile(path, bytes);

	const result = await runImagegen(path);

	expect(result.content).toEqual([
		{ text: "Generated image: generated.jpg", type: "text" },
		{ data: bytes.toString("base64"), mimeType: "image/jpeg", type: "image" },
	]);
	expect(result.details).toEqual({
		images: [{ absolute_path: path }],
		model: "gpt-image-2",
		path: "generated.jpg",
	});
});

test("imagegen retains the detected PNG MIME type", async () => {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-source-"));
	temporaryRoots.push(root);
	const path = join(root, "generated.png");
	await writeFile(path, PNG_BYTES);

	const result = await runImagegen(path);

	expect(result.content[1]).toEqual({
		data: PNG_BYTES.toString("base64"),
		mimeType: "image/png",
		type: "image",
	});
});

test("imagegen preserves the textual path when generated bytes are not a supported image", async () => {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-source-"));
	temporaryRoots.push(root);
	const path = join(root, "generated.png");
	await writeFile(path, "not an image");

	const result = await runImagegen(path);

	expect(result.content).toEqual([{ text: "Generated image: generated.jpg", type: "text" }]);
});

test("imagegen keeps the four-image inline limit", async () => {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-source-"));
	temporaryRoots.push(root);
	const paths = Array.from({ length: 5 }, (_, index) => join(root, `generated-${String(index)}.png`));
	await Promise.all(paths.map((path) => writeFile(path, PNG_BYTES)));

	const result = await executeImagegen({
		images: paths.map((path) => ({ absolute_path: path })),
		path: "generated.png",
	});

	expect(result.content.filter((content) => content.type === "image")).toHaveLength(4);
});

test("imagegen skips non-files, oversized files, and unreadable paths", async () => {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-imagegen-source-"));
	temporaryRoots.push(root);
	const directory = join(root, "directory.png");
	const oversized = join(root, "oversized.png");
	await mkdir(directory);
	await writeFile(oversized, "");
	await truncate(oversized, 25 * 1024 * 1024 + 1);

	const result = await executeImagegen({
		images: [
			{ absolute_path: directory },
			{ absolute_path: oversized },
			{ absolute_path: join(root, "missing.png") },
		],
		path: "generated.png",
	});

	expect(result.content).toEqual([{ text: "Generated image: generated.png", type: "text" }]);
});

test("imagegen rejects malformed native structured results", async () => {
	await expect(executeImagegen({ images: [], path: 42 })).rejects.toThrow(
		"imagegen returned an invalid structured result.",
	);
});
