import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { type Static, Type } from "typebox";
import { Check } from "typebox/value";

const GENERATED_HEADER = "// Generated by scripts/generate-suite.ts. Do not edit directly.";

const CAPABILITY_MODULES = {
	"conversation-ui": "conversationUi",
	"session-naming": "sessionNaming",
	"tool-display": "toolDisplay",
	"code-mode": "codeMode",
	rtk: "rtk",
	codex: "codex",
	goal: "goal",
	"context-management": "contextManagement",
	ponytail: "ponytail",
	web: "web",
	mcp: "mcp",
	"background-work": "backgroundWork",
	subagents: "subagents",
	todo: "todo",
	btw: "btw",
	notification: "notification",
} as const;

export type CapabilityModule = keyof typeof CAPABILITY_MODULES;
export type GenerationMode = "check" | "write";

export interface GenerationResult {
	changedFiles: string[];
}

const STRING_ARRAY_SCHEMA = Type.Array(Type.String(), { uniqueItems: true });
const TOOL_ARRAY_SCHEMA = Type.Array(Type.String({ minLength: 1 }), { uniqueItems: true });
export const SUITE_REGISTRY_SCHEMA = Type.Object(
	{
		$schema: Type.Optional(Type.String()),
		schemaVersion: Type.Literal(2),
		capabilities: STRING_ARRAY_SCHEMA,
		tools: TOOL_ARRAY_SCHEMA,
		deferredTools: Type.Optional(TOOL_ARRAY_SCHEMA),
		optionalTools: Type.Optional(TOOL_ARRAY_SCHEMA),
	},
	{ additionalProperties: false },
);
type SuiteRegistry = Static<typeof SUITE_REGISTRY_SCHEMA>;

async function readSuiteRegistry(path: string): Promise<SuiteRegistry> {
	const registry = JSON.parse(await readFile(path, "utf8"));
	if (!Check(SUITE_REGISTRY_SCHEMA, registry)) {
		throw new Error(`${path} must match the supported Suite registry schema`);
	}
	return registry;
}

function isCapabilityModule(value: string): value is CapabilityModule {
	return Object.hasOwn(CAPABILITY_MODULES, value);
}

function renderToolNamesConstant(identifier: string, names: readonly string[]): string {
	const inline = `const ${identifier} = [${names.map((name) => JSON.stringify(name)).join(", ")}] as const;`;
	return inline.length <= 120
		? inline
		: `const ${identifier} = [\n${names.map((name) => `\t${JSON.stringify(name)},`).join("\n")}\n] as const;`;
}

function renderCapabilityImport(capability: CapabilityModule): string {
	const identifier = CAPABILITY_MODULES[capability];
	const specifier = `./${capability}/index.ts`;
	if (capability === "tool-display") {
		return `import ${identifier}, {\n\tassertSuiteToolActivityCoverage,\n\tconfigureSuiteToolReplay,\n\tcreateSuiteToolRegistrationTracker,\n} from "${specifier}";`;
	}
	if (capability === "code-mode") {
		return `import ${identifier}, { CODE_MODE_PROVIDER_TOOL_NAMES, registerCodeModeContextProjection } from "${specifier}";`;
	}
	return `import ${identifier} from "${specifier}";`;
}

function renderRuntimeImports(capabilities: readonly CapabilityModule[], hasSubagents: boolean): string {
	// Import order is presentation-only. Keep it deterministic for Biome while the
	// capability list preserves the installation order from suite.json.
	const imports = [
		...capabilities.map((capability) => ({ id: capability, source: renderCapabilityImport(capability) })),
		{
			id: "conversation-ui/suite-lifecycle",
			source: `import {
	installSuiteSessionReadiness,
	markSuiteSessionReady,
	rejectSuiteSessionReadiness,
} from "./conversation-ui/suite-lifecycle.ts";`,
		},
		{
			id: "lifecycle-performance",
			source: 'import { markLifecyclePhase } from "./lifecycle-performance.ts";',
		},
		{
			id: "shared/effect-foundation",
			source:
				'import { completeEffectFoundationInstallation, installEffectFoundation } from "./shared/effect-foundation.ts";',
		},
		{
			id: "suite-loader",
			source: 'import type { SuiteInstallationOptions } from "./suite-loader.ts";',
		},
		...(hasSubagents
			? [
					{
						id: "subagents/pi-args",
						source:
							'import { SUBAGENT_CHILD_ENV, SUBAGENT_FANOUT_CHILD_ENV } from "./subagents/src/runs/shared/pi-args.ts";',
					},
				]
			: []),
	]
		.sort((left, right) => left.id.localeCompare(right.id))
		.map((entry) => entry.source);
	return ['import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";', ...imports].join("\n");
}

function renderCapabilityDeclaration(capabilities: readonly CapabilityModule[], sharesCodeModeState: boolean): string {
	const entries = capabilities
		.filter((capability) => capability !== "code-mode")
		.map((capability) => ({
			id: capability,
			install:
				capability === "subagents" ? "(pi) => registerSuiteSubagents(pi, options)" : CAPABILITY_MODULES[capability],
		}));
	const declaration = sharesCodeModeState
		? `function createCapabilities(
	options: SuiteInstallationOptions,
	resolveCodeModeEnabled: () => boolean,
): readonly CapabilityInstallation[] {`
		: "function createCapabilities(options: SuiteInstallationOptions): readonly CapabilityInstallation[] {";
	return `${declaration}
	return [\n${entries
		.map((entry) =>
			entry.id === "subagents" && sharesCodeModeState
				? `\t\t{
		\tid: "subagents",
		\tinstall: (pi) => registerSuiteSubagents(pi, options, resolveCodeModeEnabled, CODE_MODE_PROVIDER_TOOL_NAMES),
		},`
				: entry.id === "goal"
					? `\t\t{
		\tid: "goal",
		\tinstall: (pi) => {
		\t\tgoal(pi);
		\t},
		},`
					: `\t\t{ id: ${JSON.stringify(entry.id)}, install: ${entry.install} },`,
		)
		.join("\n")}\n\t];
}`;
}

function renderSuiteRuntime(
	capabilities: readonly CapabilityModule[],
	toolNames: readonly string[],
	optionalToolNames: readonly string[],
	deferredToolNames: readonly string[],
): string {
	const hasSubagents = capabilities.includes("subagents");
	const hasCodeMode = capabilities.includes("code-mode");
	const sharesCodeModeState = hasSubagents && hasCodeMode;
	const replayToolNames = [...toolNames, ...deferredToolNames, ...optionalToolNames];
	if ((toolNames.length > 0 || deferredToolNames.length > 0) && !capabilities.includes("tool-display")) {
		throw new Error("A Suite Tool inventory requires the tool-display module");
	}
	if (hasCodeMode && toolNames.length === 0) {
		throw new Error("The code-mode module requires a Suite Tool inventory");
	}

	const importBlock = renderRuntimeImports(capabilities, hasSubagents);
	const capabilityDeclaration = renderCapabilityDeclaration(capabilities, sharesCodeModeState);
	const coverageArguments = [
		"pi",
		"REQUIRED_SUITE_TOOL_NAMES",
		"registrations.toolNames",
		...(optionalToolNames.length > 0 || deferredToolNames.length > 0
			? [optionalToolNames.length > 0 ? "OPTIONAL_SUITE_TOOL_NAMES" : "[]"]
			: []),
		...(deferredToolNames.length > 0 ? ["DEFERRED_SUITE_TOOL_NAMES"] : []),
	];
	const coverageCall = `assertSuiteToolActivityCoverage(\n${coverageArguments
		.map((argument) => `\t\t\t\t${argument},`)
		.join("\n")}\n\t\t\t)`;
	const requiredToolNames =
		hasSubagents && toolNames.includes("subagent")
			? `const REQUIRED_SUITE_TOOL_NAMES =
	process.env[SUBAGENT_CHILD_ENV] === "1" && process.env[SUBAGENT_FANOUT_CHILD_ENV] !== "1"
		? SUITE_TOOL_NAMES.filter((name) => name !== "subagent")
		: SUITE_TOOL_NAMES;`
			: "const REQUIRED_SUITE_TOOL_NAMES = SUITE_TOOL_NAMES;";
	const sections = [
		GENERATED_HEADER,
		importBlock,
		'markLifecyclePhase("suite.module-imported");',
		`type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;

interface CapabilityInstallation {
	readonly id: string;
	readonly install: CapabilityFactory;
}`,
		...(hasSubagents
			? [
					sharesCodeModeState
						? `function registerSuiteSubagents(
	pi: ExtensionAPI,
	options: SuiteInstallationOptions,
	resolveCodeModeEnabled: () => boolean,
	codeModeProviderTools: readonly string[],
): void | Promise<void> {
	return subagents(pi, {
		childBaseExtensionPath: options.childBaseExtensionPath,
		codeModeProviderTools,
		resolveCodeModeEnabled,
	});
}`
						: `function registerSuiteSubagents(pi: ExtensionAPI, options: SuiteInstallationOptions): void | Promise<void> {
	return subagents(pi, { childBaseExtensionPath: options.childBaseExtensionPath });
}`,
				]
			: []),
		capabilityDeclaration,
		...(toolNames.length > 0
			? [
					renderToolNamesConstant("SUITE_TOOL_NAMES", toolNames),
					requiredToolNames,
					...(deferredToolNames.length > 0
						? [renderToolNamesConstant("DEFERRED_SUITE_TOOL_NAMES", deferredToolNames)]
						: []),
					...(optionalToolNames.length > 0
						? [renderToolNamesConstant("OPTIONAL_SUITE_TOOL_NAMES", optionalToolNames)]
						: []),
					...(replayToolNames.length > 0
						? [renderToolNamesConstant("REPLAY_SUITE_TOOL_NAMES", replayToolNames)]
						: []),
				]
			: []),
		`export async function installPiStuff(pi: ExtensionAPI, options: SuiteInstallationOptions): Promise<void> {
\tmarkLifecyclePhase("suite.factory.start");
\tconst suiteApi = installSuiteSessionReadiness(pi);
\t${hasCodeMode ? "const effects = " : ""}installEffectFoundation(suiteApi, { deferShutdown: true });
${toolNames.length > 0 ? "\tconst registrations = createSuiteToolRegistrationTracker(suiteApi);\n" : ""}${hasCodeMode ? "\tregisterCodeModeContextProjection(suiteApi);\n" : ""}${sharesCodeModeState ? '\tconst resolveCodeModeEnabled = () => registrations.surface.isEnvelopeEnabled("codemode");\n' : ""}\tfor (const capability of createCapabilities(options${sharesCodeModeState ? ", resolveCodeModeEnabled" : ""})) {
\t\tmarkLifecyclePhase(\`capability.\${capability.id}.start\`);
\t\tawait capability.install(${toolNames.length > 0 ? "registrations.api" : "suiteApi"});
\t\tmarkLifecyclePhase(\`capability.\${capability.id}.end\`);
\t}${hasCodeMode ? `\n\tmarkLifecyclePhase("capability.code-mode.start");\n\tcodeMode(registrations.api, {\n\t\teffects,\n\t\tregistry: registrations.registry,\n\t\tsurface: registrations.surface,\n\t});\n\tmarkLifecyclePhase("capability.code-mode.end");` : ""}
${toolNames.length > 0 ? `\n\tconfigureSuiteToolReplay(registrations.api, registrations.toolNames${replayToolNames.length > 0 ? ", REPLAY_SUITE_TOOL_NAMES" : ""});` : ""}
\tpi.on("session_start", (_event, ctx) => {
${toolNames.length > 0 ? `\t\ttry {\n\t\t\t${coverageCall};\n\t\t} catch (error) {\n\t\t\trejectSuiteSessionReadiness(pi, ctx);\n\t\t\tthrow error;\n\t\t}\n\t\tmarkSuiteSessionReady(pi, ctx);` : "\t\tmarkSuiteSessionReady(pi, ctx);"}
\t});
\tcompleteEffectFoundationInstallation(suiteApi);
\tmarkLifecyclePhase("suite.factory.end");
}`,
	];
	return `${sections.join("\n\n")}\n`;
}

function renderIndex(): string {
	return `${[
		GENERATED_HEADER,
		`import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { markLifecyclePhase } from "./src/lifecycle-performance.ts";
import { importFreshSuiteRuntime, loadSuiteRuntime } from "./src/suite-loader.ts";`,
		`const ENTRY_PATH = fileURLToPath(import.meta.url);
const SOURCE_ROOT = join(dirname(ENTRY_PATH), "src");
const RUNTIME_PATH = join(SOURCE_ROOT, "suite-runtime.ts");`,
		'markLifecyclePhase("suite.wrapper.imported");',
		`export default async function piStuff(pi: ExtensionAPI): Promise<void> {
	markLifecyclePhase("suite.wrapper.factory.start");
	const runtime = await loadSuiteRuntime({
		sourceRoot: SOURCE_ROOT,
		load: (_fingerprint, mode) =>
			mode === "initial" ? import("./src/suite-runtime.ts") : importFreshSuiteRuntime(RUNTIME_PATH),
	});
	await runtime.installPiStuff(pi, { childBaseExtensionPath: ENTRY_PATH });
	markLifecyclePhase("suite.wrapper.factory.end");
}`,
	].join("\n\n")}\n`;
}

function parseCapabilities(registry: SuiteRegistry): CapabilityModule[] {
	const capabilities: CapabilityModule[] = [];
	for (const capability of registry.capabilities) {
		if (!isCapabilityModule(capability)) {
			throw new Error(`Unknown Capability Module: ${capability}`);
		}
		capabilities.push(capability);
	}
	return capabilities;
}

function parseTools(registry: SuiteRegistry, field: "tools" | "optionalTools" | "deferredTools"): string[] {
	return registry[field] ?? [];
}

function assertDisjointTools(
	required: readonly string[],
	optional: readonly string[],
	deferred: readonly string[],
): void {
	const seen = new Set(required);
	for (const name of [...optional, ...deferred]) {
		if (seen.has(name)) throw new Error(`Suite Tool inventories overlap at ${name}`);
		seen.add(name);
	}
}

async function applyGeneratedFile(path: string, content: string, mode: GenerationMode): Promise<boolean> {
	const current = await readFile(path, "utf8").catch(() => undefined);
	if (current === content) return false;
	if (mode === "write") {
		await mkdir(dirname(path), { recursive: true });
		await writeFile(path, content);
	}
	return true;
}

export async function generateSuite(rootDirectory: string, mode: GenerationMode): Promise<GenerationResult> {
	const root = resolve(rootDirectory);
	const packageDirectory = join(root, "packages", "pi-stuff");
	const indexPath = join(packageDirectory, "index.ts");
	const runtimePath = join(packageDirectory, "src", "suite-runtime.ts");
	const registry = await readSuiteRegistry(join(packageDirectory, "suite.json"));
	const capabilities = parseCapabilities(registry);
	const requiredTools = parseTools(registry, "tools");
	const optionalTools = parseTools(registry, "optionalTools");
	const deferredTools = parseTools(registry, "deferredTools");
	assertDisjointTools(requiredTools, optionalTools, deferredTools);
	const generatedFiles = [
		[indexPath, renderIndex()],
		[runtimePath, renderSuiteRuntime(capabilities, requiredTools, optionalTools, deferredTools)],
	] as const;
	const changedFiles: string[] = [];
	for (const [path, content] of generatedFiles) {
		if (await applyGeneratedFile(path, content, mode)) changedFiles.push(relative(root, path));
	}
	if (mode === "check" && changedFiles.length > 0) {
		throw new Error(`Generated Suite files are stale: ${changedFiles.join(", ")}`);
	}
	return { changedFiles };
}

if (import.meta.main) {
	const arguments_ = process.argv.slice(2);
	if (arguments_.some((argument) => argument !== "--check")) {
		throw new Error(`Unknown arguments: ${arguments_.join(" ")}`);
	}
	const mode: GenerationMode = arguments_.includes("--check") ? "check" : "write";
	const result = await generateSuite(resolve(import.meta.dir, ".."), mode);
	if (mode === "write") {
		console.log(
			result.changedFiles.length > 0 ? `Generated ${result.changedFiles.join(", ")}` : "Suite files are current",
		);
	}
}
