// Generated by scripts/generate-suite.ts. Do not edit directly.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import backgroundWork from "./background-work/index.ts";
import btw from "./btw/index.ts";
import codeMode, { CODE_MODE_PROVIDER_TOOL_NAMES, registerCodeModeContextProjection } from "./code-mode/index.ts";
import codex from "./codex/index.ts";
import contextManagement from "./context-management/index.ts";
import conversationUi from "./conversation-ui/index.ts";
import {
	installSuiteSessionReadiness,
	markSuiteSessionReady,
	rejectSuiteSessionReadiness,
} from "./conversation-ui/suite-lifecycle.ts";
import goal from "./goal/index.ts";
import { markLifecyclePhase } from "./lifecycle-performance.ts";
import mcp from "./mcp/index.ts";
import notification from "./notification/index.ts";
import ponytail from "./ponytail/index.ts";
import rtk from "./rtk/index.ts";
import sessionNaming from "./session-naming/index.ts";
import { completeEffectFoundationInstallation, installEffectFoundation } from "./shared/effect-foundation.ts";
import subagents from "./subagents/index.ts";
import { SUBAGENT_CHILD_ENV, SUBAGENT_FANOUT_CHILD_ENV } from "./subagents/src/runs/shared/pi-args.ts";
import type { SuiteInstallationOptions } from "./suite-loader.ts";
import todo from "./todo/index.ts";
import toolDisplay, {
	assertSuiteToolActivityCoverage,
	configureSuiteToolReplay,
	createSuiteToolRegistrationTracker,
} from "./tool-display/index.ts";
import web from "./web/index.ts";

markLifecyclePhase("suite.module-imported");

type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;

interface CapabilityInstallation {
	readonly id: string;
	readonly install: CapabilityFactory;
}

function registerSuiteSubagents(
	pi: ExtensionAPI,
	options: SuiteInstallationOptions,
	resolveCodeModeEnabled: () => boolean,
	codeModeProviderTools: readonly string[],
): void | Promise<void> {
	return subagents(pi, {
		childBaseExtensionPath: options.childBaseExtensionPath,
		codeModeProviderTools,
		resolveCodeModeEnabled,
	});
}

function createCapabilities(
	options: SuiteInstallationOptions,
	resolveCodeModeEnabled: () => boolean,
): readonly CapabilityInstallation[] {
	return [
		{ id: "conversation-ui", install: conversationUi },
		{ id: "session-naming", install: sessionNaming },
		{ id: "tool-display", install: toolDisplay },
		{ id: "rtk", install: rtk },
		{ id: "codex", install: codex },
		{
			id: "goal",
			install: (pi) => {
				goal(pi);
			},
		},
		{ id: "context-management", install: contextManagement },
		{ id: "ponytail", install: ponytail },
		{ id: "web", install: web },
		{ id: "mcp", install: mcp },
		{ id: "background-work", install: backgroundWork },
		{
			id: "subagents",
			install: (pi) => registerSuiteSubagents(pi, options, resolveCodeModeEnabled, CODE_MODE_PROVIDER_TOOL_NAMES),
		},
		{ id: "todo", install: todo },
		{ id: "btw", install: btw },
		{ id: "notification", install: notification },
	];
}

const SUITE_TOOL_NAMES = [
	"read",
	"write",
	"edit",
	"grep",
	"find",
	"ls",
	"bash",
	"apply_patch",
	"view_image",
	"imagegen",
	"goal_complete",
	"goal_blocked",
	"web_search",
	"fetch_content",
	"get_search_content",
	"mcp",
	"background",
	"monitor",
	"subagent",
	"TaskCreate",
	"TaskGet",
	"TaskList",
	"TaskUpdate",
] as const;

const REQUIRED_SUITE_TOOL_NAMES =
	process.env[SUBAGENT_CHILD_ENV] === "1" && process.env[SUBAGENT_FANOUT_CHILD_ENV] !== "1"
		? SUITE_TOOL_NAMES.filter((name) => name !== "subagent")
		: SUITE_TOOL_NAMES;

const DEFERRED_SUITE_TOOL_NAMES = ["ctx_expand", "ctx_search", "ctx_memory", "ctx_note", "ctx_reduce"] as const;

const OPTIONAL_SUITE_TOOL_NAMES = [
	"subagent_supervisor",
	"intercom",
	"contact_supervisor",
	"structured_output",
] as const;

const REPLAY_SUITE_TOOL_NAMES = [
	"read",
	"write",
	"edit",
	"grep",
	"find",
	"ls",
	"bash",
	"apply_patch",
	"view_image",
	"imagegen",
	"goal_complete",
	"goal_blocked",
	"web_search",
	"fetch_content",
	"get_search_content",
	"mcp",
	"background",
	"monitor",
	"subagent",
	"TaskCreate",
	"TaskGet",
	"TaskList",
	"TaskUpdate",
	"ctx_expand",
	"ctx_search",
	"ctx_memory",
	"ctx_note",
	"ctx_reduce",
	"subagent_supervisor",
	"intercom",
	"contact_supervisor",
	"structured_output",
] as const;

export async function installPiStuff(pi: ExtensionAPI, options: SuiteInstallationOptions): Promise<void> {
	markLifecyclePhase("suite.factory.start");
	const suiteApi = installSuiteSessionReadiness(pi);
	const effects = installEffectFoundation(suiteApi, { deferShutdown: true });
	const registrations = createSuiteToolRegistrationTracker(suiteApi);
	registerCodeModeContextProjection(suiteApi);
	const resolveCodeModeEnabled = () => registrations.surface.isEnvelopeEnabled("codemode");
	for (const capability of createCapabilities(options, resolveCodeModeEnabled)) {
		markLifecyclePhase(`capability.${capability.id}.start`);
		await capability.install(registrations.api);
		markLifecyclePhase(`capability.${capability.id}.end`);
	}
	markLifecyclePhase("capability.code-mode.start");
	codeMode(registrations.api, {
		effects,
		registry: registrations.registry,
		surface: registrations.surface,
	});
	markLifecyclePhase("capability.code-mode.end");

	configureSuiteToolReplay(registrations.api, registrations.toolNames, REPLAY_SUITE_TOOL_NAMES);
	pi.on("session_start", (_event, ctx) => {
		try {
			assertSuiteToolActivityCoverage(
				pi,
				REQUIRED_SUITE_TOOL_NAMES,
				registrations.toolNames,
				OPTIONAL_SUITE_TOOL_NAMES,
				DEFERRED_SUITE_TOOL_NAMES,
			);
		} catch (error) {
			rejectSuiteSessionReadiness(pi, ctx);
			throw error;
		}
		markSuiteSessionReady(pi, ctx);
	});
	completeEffectFoundationInstallation(suiteApi);
	markLifecyclePhase("suite.factory.end");
}
